In [1]:
%load_ext sql
%sql mysql://sywang@localhost/?charset=utf8mb4

In [2]:
database = 'sywang_project' ## THIS IS YOUR SUNETID
msgs_table = 'msgs'
topics_cp_table = 'ags_cp'
topics_freq_table = 'ags_freq'

In [3]:
%sql use {database}

 * mysql://sywang@localhost/?charset=utf8mb4
0 rows affected.

[]

# Extract topics, by user, from the 1-gram tables

In [35]:
!dlatkInterface.py \
    --corpdb {database} \
    --corptable msgs \
    --correl_field user_id \
    --lexicondb {database} \
    --add_lex_table -l {topics_cp_table} --weighted_lexicon

/shared/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.linear_model.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)
/shared/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.feature_selection.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.feature_selection. Anything that cannot be imported from sklearn.feature_selection is now part of the private API.
  warnings.warn(message, FutureWarning)


-----
DLATK Interface Initiated: 2020-11-16 06:53:23
-----
SQL QUERY: SELECT * FROM sywang_project.ags_cp
SQL QUERY: SELECT column_type FROM information_schema.columns WHERE table_schema='sywang_project' AND table_name='msgs' AND column_name='user_id'
SQL QUERY: DROP TABLE IF EXISTS feat$cat_ags_cp_w$msgs$user_id$1gra
SQL QUERY: CREATE TABLE feat$cat_ags_cp_w$msgs$user_id$1gra (id BIGINT(16) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                 group_id int(11), feat VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, value INTEGER, group_norm DOUBLE,

WORD TABLE feat$1gram$msgs$user_id$16to16
SQL QUERY: show tables like 'feat$1gram$msgs$user_id$16to16'
SQL QUERY: ALTER TABLE feat$cat_ags_cp_w$msgs$user_id$1gra DISABLE KEYS
3 out of 398 group Id's processed; 0.01 complete
6 out of 398 group Id's processed; 0.02 complete
9 out of 398 group Id's processed; 0.02 complete
12 out of 398 group Id's processed; 0.03 complete
15 out of 398 group Id's processed; 0.04 complete
18 out of 398 group Id's processed; 0.05 complete
21 out of 398 group Id's processed; 0.05 complete
24 out of 398 group Id's processed; 0.06 complete
27 out of 398 group Id's processed; 0.07 complete
30 out of 398 group Id's processed; 0.08 complete
33 out of 398 group Id's processed; 0.08 complete
36 out of 398 group Id's processed; 0.09 complete
39 out of 398 group Id's processed; 0.10 complete
42 out of 398 group Id's processed; 0.11 complete
45 out of 398 group Id's processed; 0.11 complete
48 out of 398 group Id's processed; 0.12 complete
51 out of 398 group Id's processed; 0.13 complete
54 out of 398 group Id's processed; 0.14 complete
57 out of 398 group Id's processed; 0.14 complete
60 out of 398 group Id's processed; 0.15 complete
63 out of 398 group Id's processed; 0.16 complete
66 out of 398 group Id's processed; 0.17 complete
69 out of 398 group Id's processed; 0.17 complete
72 out of 398 group Id's processed; 0.18 complete
75 out of 398 group Id's processed; 0.19 complete
78 out of 398 group Id's processed; 0.20 complete
81 out of 398 group Id's processed; 0.20 complete
84 out of 398 group Id's processed; 0.21 complete
87 out of 398 group Id's processed; 0.22 complete
90 out of 398 group Id's processed; 0.23 complete
93 out of 398 group Id's processed; 0.23 complete
96 out of 398 group Id's processed; 0.24 complete
99 out of 398 group Id's processed; 0.25 complete
102 out of 398 group Id's processed; 0.26 complete
105 out of 398 group Id's processed; 0.26 complete
108 out of 398 group Id's processed; 0.27 complete
111 out of 398 group Id's processed; 0.28 complete
114 out of 398 group Id's processed; 0.29 complete
117 out of 398 group Id's processed; 0.29 complete
120 out of 398 group Id's processed; 0.30 complete
123 out of 398 group Id's processed; 0.31 complete
126 out of 398 group Id's processed; 0.32 complete
129 out of 398 group Id's processed; 0.32 complete
132 out of 398 group Id's processed; 0.33 complete
135 out of 398 group Id's processed; 0.34 complete
138 out of 398 group Id's processed; 0.35 complete
141 out of 398 group Id's processed; 0.35 complete
144 out of 398 group Id's processed; 0.36 complete
147 out of 398 group Id's processed; 0.37 complete
150 out of 398 group Id's processed; 0.38 complete
153 out of 398 group Id's processed; 0.38 complete
156 out of 398 group Id's processed; 0.39 complete
159 out of 398 group Id's processed; 0.40 complete
162 out of 398 group Id's processed; 0.41 complete
165 out of 398 group Id's processed; 0.41 complete
168 out of 398 group Id's processed; 0.42 complete
171 out of 398 group Id's processed; 0.43 complete
174 out of 398 group Id's processed; 0.44 complete
177 out of 398 group Id's processed; 0.44 complete
180 out of 398 group Id's processed; 0.45 complete
183 out of 398 group Id's processed; 0.46 complete
186 out of 398 group Id's processed; 0.47 complete
189 out of 398 group Id's processed; 0.47 complete
192 out of 398 group Id's processed; 0.48 complete
195 out of 398 group Id's processed; 0.49 complete
198 out of 398 group Id's processed; 0.50 complete
201 out of 398 group Id's processed; 0.51 complete
204 out of 398 group Id's processed; 0.51 complete
207 out of 398 group Id's processed; 0.52 complete
210 out of 398 group Id's processed; 0.53 complete
213 out of 398 group Id's processed; 0.54 complete
216 out of 398 group Id's processed; 0.54 complete
219 out of 398 group Id's processed; 0.55 complete
222 out of 398 group Id's processed; 0.56 complete
225 out of 398 group Id's processed; 0.57 complete
228 out of 398 group Id's processed; 0.57 complete
231 out of 398 group Id's processed; 0.58 complete
234 out of 398 group Id's processed; 0.59 complete
237 out of 398 group Id's processed; 0.60 complete
240 out of 398 group Id's processed; 0.60 complete
243 out of 398 group Id's processed; 0.61 complete
246 out of 398 group Id's processed; 0.62 complete
249 out of 398 group Id's processed; 0.63 complete
252 out of 398 group Id's processed; 0.63 complete
255 out of 398 group Id's processed; 0.64 complete
258 out of 398 group Id's processed; 0.65 complete
261 out of 398 group Id's processed; 0.66 complete
264 out of 398 group Id's processed; 0.66 complete
267 out of 398 group Id's processed; 0.67 complete
270 out of 398 group Id's processed; 0.68 complete
273 out of 398 group Id's processed; 0.69 complete
276 out of 398 group Id's processed; 0.69 complete
279 out of 398 group Id's processed; 0.70 complete
282 out of 398 group Id's processed; 0.71 complete
285 out of 398 group Id's processed; 0.72 complete
288 out of 398 group Id's processed; 0.72 complete
291 out of 398 group Id's processed; 0.73 complete
294 out of 398 group Id's processed; 0.74 complete
297 out of 398 group Id's processed; 0.75 complete
300 out of 398 group Id's processed; 0.75 complete
303 out of 398 group Id's processed; 0.76 complete
306 out of 398 group Id's processed; 0.77 complete
309 out of 398 group Id's processed; 0.78 complete
312 out of 398 group Id's processed; 0.78 complete
315 out of 398 group Id's processed; 0.79 complete
318 out of 398 group Id's processed; 0.80 complete
321 out of 398 group Id's processed; 0.81 complete
324 out of 398 group Id's processed; 0.81 complete
327 out of 398 group Id's processed; 0.82 complete
330 out of 398 group Id's processed; 0.83 complete
333 out of 398 group Id's processed; 0.84 complete
336 out of 398 group Id's processed; 0.84 complete
339 out of 398 group Id's processed; 0.85 complete
342 out of 398 group Id's processed; 0.86 complete
345 out of 398 group Id's processed; 0.87 complete
348 out of 398 group Id's processed; 0.87 complete
351 out of 398 group Id's processed; 0.88 complete
354 out of 398 group Id's processed; 0.89 complete
357 out of 398 group Id's processed; 0.90 complete
360 out of 398 group Id's processed; 0.90 complete
363 out of 398 group Id's processed; 0.91 complete
366 out of 398 group Id's processed; 0.92 complete
369 out of 398 group Id's processed; 0.93 complete
372 out of 398 group Id's processed; 0.93 complete
375 out of 398 group Id's processed; 0.94 complete
378 out of 398 group Id's processed; 0.95 complete
381 out of 398 group Id's processed; 0.96 complete
384 out of 398 group Id's processed; 0.96 complete
387 out of 398 group Id's processed; 0.97 complete
390 out of 398 group Id's processed; 0.98 complete
393 out of 398 group Id's processed; 0.99 complete
396 out of 398 group Id's processed; 0.99 complete
398 out of 398 group Id's processed; 1.00 complete
SQL QUERY: ALTER TABLE feat$cat_ags_cp_w$msgs$user_id$1gra ENABLE KEYS
--
Interface Runtime: 0.87 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

this creates the topics table 
feat$cat_ags_cp_w$msgs$user_id$1gra

In [50]:
feat_topics_table = 'feat$cat_ags_cp_w$msgs$user_id$1gra'

In [51]:
%%sql
select feat, sum(group_norm)/398 as popularity from {feat_topics_table}
group by feat 
order by popularity desc
limit 10

 * mysql://sywang@localhost/?charset=utf8mb4
10 rows affected.

[('_intercept', 1.0),
 ('29', 0.016369938879875517),
 ('16', 0.013623617191025875),
 ('19', 0.013533974481477598),
 ('0', 0.011640597280189062),
 ('1', 0.011244759020684966),
 ('2', 0.010610960133728229),
 ('35', 0.01003618425463437),
 ('7', 0.009936567539457323),
 ('38', 0.009685352017105502)]

In [52]:
%%sql
use {database};
select category, group_concat(term order by weight desc separator ', ') as top_words from (
    select category, term, weight,
    @num := if(@type = category, @num + 1, 1) as row_number,
    @type := category as dummy
    from {topics_freq_table}
    order by category, weight desc
) as x where x.row_number <= 10
group by category
having category like "29" or category like "16"  or category like "19" or category like "0" or category like "1";

 * mysql://sywang@localhost/?charset=utf8mb4
0 rows affected.
5 rows affected.

[('0', 'practice, contact, interested, full, clinic, care, opportunity, email, position, feel'),
 ('1', 'year, advice, history, thoughts, cell, beach, meds, slt, months, presented'),
 ('16', 'tube, technique, good, sclera, cornea, scleral, conj, luck, patch, graft'),
 ('19', 'glaucoma, patient, specialist, recommendations, moving, area, center, dear, cataract, recommend'),
 ('29', 'iop, years, ago, weeks, back, ahmed, week, bleb, post, retina')]

# Extract topics, by all message, from the 1-gram tables

In [39]:
!dlatkInterface.py \
    --corpdb {database} \
    --corptable msgs \
    --correl_field message_id \
    --lexicondb {database} \
    --add_lex_table -l {topics_cp_table} --weighted_lexicon

/shared/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.linear_model.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)
/shared/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.feature_selection.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.feature_selection. Anything that cannot be imported from sklearn.feature_selection is now part of the private API.
  warnings.warn(message, FutureWarning)


-----
DLATK Interface Initiated: 2020-11-16 06:53:51
-----
SQL QUERY: SELECT * FROM sywang_project.ags_cp
SQL QUERY: SELECT column_type FROM information_schema.columns WHERE table_schema='sywang_project' AND table_name='msgs' AND column_name='message_id'
SQL QUERY: DROP TABLE IF EXISTS feat$cat_ags_cp_w$msgs$message_id$1gra
SQL QUERY: CREATE TABLE feat$cat_ags_cp_w$msgs$message_id$1gra (id BIGINT(16) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                 group_id bigint(20), feat VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, value INTEGER, group_norm DOUBLE,

WORD TABLE feat$1gram$msgs$message_id$16to16
SQL QUERY: show tables like 'feat$1gram$msgs$message_id$16to16'
SQL QUERY: ALTER TABLE feat$cat_ags_cp_w$msgs$message_id$1gra DISABLE KEYS
19 out of 1908 group Id's processed; 0.01 complete
38 out of 1908 group Id's processed; 0.02 complete
57 out of 1908 group Id's processed; 0.03 complete
76 out of 1908 group Id's processed; 0.04 complete
95 out of 1908 group Id's processed; 0.05 complete
114 out of 1908 group Id's processed; 0.06 complete
133 out of 1908 group Id's processed; 0.07 complete
152 out of 1908 group Id's processed; 0.08 complete
171 out of 1908 group Id's processed; 0.09 complete
190 out of 1908 group Id's processed; 0.10 complete
209 out of 1908 group Id's processed; 0.11 complete
228 out of 1908 group Id's processed; 0.12 complete
247 out of 1908 group Id's processed; 0.13 complete
266 out of 1908 group Id's processed; 0.14 complete
285 out of 1908 group Id's processed; 0.15 complete
304 out of 1908 group Id's processed; 0.16 complete
323 out of 1908 group Id's processed; 0.17 complete
342 out of 1908 group Id's processed; 0.18 complete
361 out of 1908 group Id's processed; 0.19 complete
380 out of 1908 group Id's processed; 0.20 complete
399 out of 1908 group Id's processed; 0.21 complete
418 out of 1908 group Id's processed; 0.22 complete
437 out of 1908 group Id's processed; 0.23 complete
456 out of 1908 group Id's processed; 0.24 complete
475 out of 1908 group Id's processed; 0.25 complete
494 out of 1908 group Id's processed; 0.26 complete
513 out of 1908 group Id's processed; 0.27 complete
532 out of 1908 group Id's processed; 0.28 complete
551 out of 1908 group Id's processed; 0.29 complete
570 out of 1908 group Id's processed; 0.30 complete
589 out of 1908 group Id's processed; 0.31 complete
608 out of 1908 group Id's processed; 0.32 complete
627 out of 1908 group Id's processed; 0.33 complete
646 out of 1908 group Id's processed; 0.34 complete
665 out of 1908 group Id's processed; 0.35 complete
684 out of 1908 group Id's processed; 0.36 complete
703 out of 1908 group Id's processed; 0.37 complete
722 out of 1908 group Id's processed; 0.38 complete
741 out of 1908 group Id's processed; 0.39 complete
760 out of 1908 group Id's processed; 0.40 complete
779 out of 1908 group Id's processed; 0.41 complete
798 out of 1908 group Id's processed; 0.42 complete
817 out of 1908 group Id's processed; 0.43 complete
836 out of 1908 group Id's processed; 0.44 complete
855 out of 1908 group Id's processed; 0.45 complete
874 out of 1908 group Id's processed; 0.46 complete
893 out of 1908 group Id's processed; 0.47 complete
912 out of 1908 group Id's processed; 0.48 complete
931 out of 1908 group Id's processed; 0.49 complete
950 out of 1908 group Id's processed; 0.50 complete
969 out of 1908 group Id's processed; 0.51 complete
988 out of 1908 group Id's processed; 0.52 complete
1007 out of 1908 group Id's processed; 0.53 complete
1026 out of 1908 group Id's processed; 0.54 complete
1045 out of 1908 group Id's processed; 0.55 complete
1064 out of 1908 group Id's processed; 0.56 complete
1083 out of 1908 group Id's processed; 0.57 complete
1102 out of 1908 group Id's processed; 0.58 complete
1121 out of 1908 group Id's processed; 0.59 complete
1140 out of 1908 group Id's processed; 0.60 complete
1159 out of 1908 group Id's processed; 0.61 complete
1178 out of 1908 group Id's processed; 0.62 complete
1197 out of 1908 group Id's processed; 0.63 complete
1216 out of 1908 group Id's processed; 0.64 complete
1235 out of 1908 group Id's processed; 0.65 complete
1254 out of 1908 group Id's processed; 0.66 complete
1273 out of 1908 group Id's processed; 0.67 complete
1292 out of 1908 group Id's processed; 0.68 complete
1311 out of 1908 group Id's processed; 0.69 complete
1330 out of 1908 group Id's processed; 0.70 complete
1349 out of 1908 group Id's processed; 0.71 complete
1368 out of 1908 group Id's processed; 0.72 complete
1387 out of 1908 group Id's processed; 0.73 complete
1406 out of 1908 group Id's processed; 0.74 complete
1425 out of 1908 group Id's processed; 0.75 complete
1444 out of 1908 group Id's processed; 0.76 complete
1463 out of 1908 group Id's processed; 0.77 complete
1482 out of 1908 group Id's processed; 0.78 complete
1501 out of 1908 group Id's processed; 0.79 complete
1520 out of 1908 group Id's processed; 0.80 complete
1539 out of 1908 group Id's processed; 0.81 complete
1558 out of 1908 group Id's processed; 0.82 complete
1577 out of 1908 group Id's processed; 0.83 complete
1596 out of 1908 group Id's processed; 0.84 complete
1615 out of 1908 group Id's processed; 0.85 complete
1634 out of 1908 group Id's processed; 0.86 complete
1653 out of 1908 group Id's processed; 0.87 complete
1672 out of 1908 group Id's processed; 0.88 complete
1691 out of 1908 group Id's processed; 0.89 complete
1710 out of 1908 group Id's processed; 0.90 complete
1729 out of 1908 group Id's processed; 0.91 complete
1748 out of 1908 group Id's processed; 0.92 complete
1767 out of 1908 group Id's processed; 0.93 complete
1786 out of 1908 group Id's processed; 0.94 complete
1805 out of 1908 group Id's processed; 0.95 complete
1824 out of 1908 group Id's processed; 0.96 complete
1843 out of 1908 group Id's processed; 0.97 complete
1862 out of 1908 group Id's processed; 0.98 complete
1881 out of 1908 group Id's processed; 0.99 complete
1900 out of 1908 group Id's processed; 1.00 complete
1908 out of 1908 group Id's processed; 1.00 complete
SQL QUERY: ALTER TABLE feat$cat_ags_cp_w$msgs$message_id$1gra ENABLE KEYS
--
Interface Runtime: 2.12 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

this creates the topics table 
feat$cat_ags_cp_w$msgs$message_id$1gra

In [53]:
feat_topics_table = 'feat$cat_ags_cp_w$msgs$message_id$1gra'

In [54]:
%%sql
select feat, sum(group_norm)/1908 as popularity from {feat_topics_table}
group by feat 
order by popularity desc
limit 10

 * mysql://sywang@localhost/?charset=utf8mb4
10 rows affected.

[('_intercept', 1.0),
 ('16', 0.014534076114026153),
 ('29', 0.014434612216371217),
 ('10', 0.012136173771889051),
 ('35', 0.011453994156584463),
 ('2', 0.011318366471513203),
 ('20', 0.010558412555087642),
 ('30', 0.010389023943702717),
 ('36', 0.01017775156965893),
 ('5', 0.00982265532684183)]

In [55]:
%%sql
use {database};
select category, group_concat(term order by weight desc separator ', ') as top_words from (
    select category, term, weight,
    @num := if(@type = category, @num + 1, 1) as row_number,
    @type := category as dummy
    from {topics_freq_table}
    order by category, weight desc
) as x where x.row_number <= 10
group by category
having category like "16" or category like "29"  or category like "10" or category like "35" or category like "2";

 * mysql://sywang@localhost/?charset=utf8mb4
0 rows affected.
5 rows affected.

[('2', 'angle, cataract, closure, iris, lens, open, case, eyes, clear, anterior'),
 ('10', 'glaucoma, daniel, advanced, treated, eyecare, https://youtu.be, specialist, president, laroche, www.advancedeyecareny.com'),
 ('16', 'tube, technique, good, sclera, cornea, scleral, conj, luck, patch, graft'),
 ('29', 'iop, years, ago, weeks, back, ahmed, week, bleb, post, retina'),
 ('35', "iris, i've, experience, agree, angle, work, luck, cut, phaco, easily")]

# Extract topics, by all threadheads, from the 1-gram tables

In [43]:
!dlatkInterface.py \
    --corpdb {database} \
    --corptable threadheads \
    --correl_field thread_id \
    --lexicondb {database} \
    --add_lex_table -l {topics_cp_table} --weighted_lexicon

/shared/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.linear_model.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)
/shared/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.feature_selection.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.feature_selection. Anything that cannot be imported from sklearn.feature_selection is now part of the private API.
  warnings.warn(message, FutureWarning)


-----
DLATK Interface Initiated: 2020-11-16 06:54:24
-----
SQL QUERY: SELECT * FROM sywang_project.ags_cp
SQL QUERY: SELECT column_type FROM information_schema.columns WHERE table_schema='sywang_project' AND table_name='threadheads' AND column_name='thread_id'
SQL QUERY: DROP TABLE IF EXISTS feat$cat_ags_cp_w$threadheads$thread_id$1gra
SQL QUERY: CREATE TABLE feat$cat_ags_cp_w$threadheads$thread_id$1gra (id BIGINT(16) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
                 group_id bigint(20), feat VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin, value INTEGER, group_norm DOUBLE,

WORD TABLE feat$1gram$threadheads$thread_id$16to16
SQL QUERY: show tables like 'feat$1gram$threadheads$thread_id$16to16'
SQL QUERY: ALTER TABLE feat$cat_ags_cp_w$threadheads$thread_id$1gra DISABLE KEYS
5 out of 542 group Id's processed; 0.01 complete
10 out of 542 group Id's processed; 0.02 complete
15 out of 542 group Id's processed; 0.03 complete
20 out of 542 group Id's processed; 0.04 complete
25 out of 542 group Id's processed; 0.05 complete
30 out of 542 group Id's processed; 0.06 complete
35 out of 542 group Id's processed; 0.06 complete
40 out of 542 group Id's processed; 0.07 complete
45 out of 542 group Id's processed; 0.08 complete
50 out of 542 group Id's processed; 0.09 complete
55 out of 542 group Id's processed; 0.10 complete
60 out of 542 group Id's processed; 0.11 complete
65 out of 542 group Id's processed; 0.12 complete
70 out of 542 group Id's processed; 0.13 complete
75 out of 542 group Id's processed; 0.14 complete
80 out of 542 group Id's processed; 0.15 complete
85 out of 542 group Id's processed; 0.16 complete
90 out of 542 group Id's processed; 0.17 complete
95 out of 542 group Id's processed; 0.18 complete
100 out of 542 group Id's processed; 0.18 complete
105 out of 542 group Id's processed; 0.19 complete
110 out of 542 group Id's processed; 0.20 complete
115 out of 542 group Id's processed; 0.21 complete
120 out of 542 group Id's processed; 0.22 complete
125 out of 542 group Id's processed; 0.23 complete
130 out of 542 group Id's processed; 0.24 complete
135 out of 542 group Id's processed; 0.25 complete
140 out of 542 group Id's processed; 0.26 complete
145 out of 542 group Id's processed; 0.27 complete
150 out of 542 group Id's processed; 0.28 complete
155 out of 542 group Id's processed; 0.29 complete
160 out of 542 group Id's processed; 0.30 complete
165 out of 542 group Id's processed; 0.30 complete
170 out of 542 group Id's processed; 0.31 complete
175 out of 542 group Id's processed; 0.32 complete
180 out of 542 group Id's processed; 0.33 complete
185 out of 542 group Id's processed; 0.34 complete
190 out of 542 group Id's processed; 0.35 complete
195 out of 542 group Id's processed; 0.36 complete
200 out of 542 group Id's processed; 0.37 complete
205 out of 542 group Id's processed; 0.38 complete
210 out of 542 group Id's processed; 0.39 complete
215 out of 542 group Id's processed; 0.40 complete
220 out of 542 group Id's processed; 0.41 complete
225 out of 542 group Id's processed; 0.42 complete
230 out of 542 group Id's processed; 0.42 complete
235 out of 542 group Id's processed; 0.43 complete
240 out of 542 group Id's processed; 0.44 complete
245 out of 542 group Id's processed; 0.45 complete
250 out of 542 group Id's processed; 0.46 complete
255 out of 542 group Id's processed; 0.47 complete
260 out of 542 group Id's processed; 0.48 complete
265 out of 542 group Id's processed; 0.49 complete
270 out of 542 group Id's processed; 0.50 complete
275 out of 542 group Id's processed; 0.51 complete
280 out of 542 group Id's processed; 0.52 complete
285 out of 542 group Id's processed; 0.53 complete
290 out of 542 group Id's processed; 0.54 complete
295 out of 542 group Id's processed; 0.54 complete
300 out of 542 group Id's processed; 0.55 complete
305 out of 542 group Id's processed; 0.56 complete
310 out of 542 group Id's processed; 0.57 complete
315 out of 542 group Id's processed; 0.58 complete
320 out of 542 group Id's processed; 0.59 complete
325 out of 542 group Id's processed; 0.60 complete
330 out of 542 group Id's processed; 0.61 complete
335 out of 542 group Id's processed; 0.62 complete
340 out of 542 group Id's processed; 0.63 complete
345 out of 542 group Id's processed; 0.64 complete
350 out of 542 group Id's processed; 0.65 complete
355 out of 542 group Id's processed; 0.65 complete
360 out of 542 group Id's processed; 0.66 complete
365 out of 542 group Id's processed; 0.67 complete
370 out of 542 group Id's processed; 0.68 complete
375 out of 542 group Id's processed; 0.69 complete
380 out of 542 group Id's processed; 0.70 complete
385 out of 542 group Id's processed; 0.71 complete
390 out of 542 group Id's processed; 0.72 complete
395 out of 542 group Id's processed; 0.73 complete
400 out of 542 group Id's processed; 0.74 complete
405 out of 542 group Id's processed; 0.75 complete
410 out of 542 group Id's processed; 0.76 complete
415 out of 542 group Id's processed; 0.77 complete
420 out of 542 group Id's processed; 0.77 complete
425 out of 542 group Id's processed; 0.78 complete
430 out of 542 group Id's processed; 0.79 complete
435 out of 542 group Id's processed; 0.80 complete
440 out of 542 group Id's processed; 0.81 complete
445 out of 542 group Id's processed; 0.82 complete
450 out of 542 group Id's processed; 0.83 complete
455 out of 542 group Id's processed; 0.84 complete
460 out of 542 group Id's processed; 0.85 complete
465 out of 542 group Id's processed; 0.86 complete
470 out of 542 group Id's processed; 0.87 complete
475 out of 542 group Id's processed; 0.88 complete
480 out of 542 group Id's processed; 0.89 complete
485 out of 542 group Id's processed; 0.89 complete
490 out of 542 group Id's processed; 0.90 complete
495 out of 542 group Id's processed; 0.91 complete
500 out of 542 group Id's processed; 0.92 complete
505 out of 542 group Id's processed; 0.93 complete
510 out of 542 group Id's processed; 0.94 complete
515 out of 542 group Id's processed; 0.95 complete
520 out of 542 group Id's processed; 0.96 complete
525 out of 542 group Id's processed; 0.97 complete
530 out of 542 group Id's processed; 0.98 complete
535 out of 542 group Id's processed; 0.99 complete
540 out of 542 group Id's processed; 1.00 complete
542 out of 542 group Id's processed; 1.00 complete
SQL QUERY: ALTER TABLE feat$cat_ags_cp_w$threadheads$thread_id$1gra ENABLE KEYS
--
Interface Runtime: 0.71 seconds
DLATK exits with success! A good day indeed  ¯\_(ツ)_/¯.

this creates the topics table 
feat$cat_ags_cp_w$msgs$message_id$1gra

In [56]:
feat_topics_table = 'feat$cat_ags_cp_w$threadheads$thread_id$1gra'

In [57]:
%%sql
select feat, sum(group_norm)/542 as popularity from {feat_topics_table}
group by feat 
order by popularity desc
limit 10

 * mysql://sywang@localhost/?charset=utf8mb4
10 rows affected.

[('_intercept', 1.0),
 ('19', 0.019674787930452107),
 ('0', 0.01520218223181562),
 ('29', 0.014867024779109516),
 ('8', 0.0142718412116267),
 ('1', 0.012911207731654965),
 ('20', 0.011923942796892795),
 ('16', 0.011183446091589166),
 ('25', 0.011085273885385053),
 ('2', 0.010235657535197246)]

In [58]:
%%sql
use {database};
select category, group_concat(term order by weight desc separator ', ') as top_words from (
    select category, term, weight,
    @num := if(@type = category, @num + 1, 1) as row_number,
    @type := category as dummy
    from {topics_freq_table}
    order by category, weight desc
) as x where x.row_number <= 10
group by category
having category like "19" or category like "0"  or category like "29" or category like "8" or category like "1";

 * mysql://sywang@localhost/?charset=utf8mb4
0 rows affected.
5 rows affected.

[('0', 'practice, contact, interested, full, clinic, care, opportunity, email, position, feel'),
 ('1', 'year, advice, history, thoughts, cell, beach, meds, slt, months, presented'),
 ('8', 'ags, aao, members, questions, dear, link, society, org, american, committee'),
 ('19', 'glaucoma, patient, specialist, recommendations, moving, area, center, dear, cataract, recommend'),
 ('29', 'iop, years, ago, weeks, back, ahmed, week, bleb, post, retina')]